# Server configurations
server:
  environment: "development"
  host: "localhost"
  port: 8008
  logpath: "../gounico/logs/gounico.log"
listener:
  environment: "development"
  host: "localhost"
  port: 8009
database:
  table: "feiras"
  region: "us-east-1"
  accessKeyID: "dummy"
  secretAccessKey: "dummy"
  sessionToken: "dummy"
  endpointURL: "http://127.0.0.1:8000"
messaging:
  brokerURL: "pulsar://localhost:6650"
  workerPoolLimit: 500
  channelConsumerLimit: 500
  configurations: [
    { topic: "feiraLivre", subscriber: "feiraSub", url: "http://localhost:8009/consumers/novafeira" },
  ]
telemetry:
    jaegerEndpoint: "http://localhost:14268/api/traces"
    appName: "feiralivre"