# Server configurations
server:
  environment: "development"
  host: "localhost"
  port: 8008
  logpath: "../gounico/logs/gounico.log"
worker:
  environment: "development"
  host: "localhost"
  port: 8009
database:
  table: "feiras"
  region: "us-east-1"
  accessKeyID: "dummy"
  secretAccessKey: "dummy"
  sessionToken: "dummy"
  endpointURL: "http://127.0.0.1:8000"