# Server configurations
server:
  environment: "development"
  host: "host.docker.internal"
  port: 8008
  logpath: "../gounico/logs/gounico.log"
database:
  table: "feiras"
  region: "us-east-1"
  accessKeyID: "dummy"
  secretAccessKey: "dummy"
  sessionToken: "dummy"
  endpointURL: "http://localhost:8000"