# Server configurations
server:
  environment: "development"
  host: "localhost"
  port: 8000
  logpath: "../gounico/logs/gounico.log"
database:
    DB_USERNAME : "root"
    DB_PASSWORD : "root"
    DB_NAME : "gounico"
    DB_HOST : "172.17.0.2"
    DB_PORT : "3306"