# Server configurations
server:
  environment: "development"
  host: "host.docker.internal"
  port: 8000
  logpath: "../gounico/logs/gounico.log"
database:
    DB_USERNAME : "root"
    DB_PASSWORD : "root"
    DB_NAME : "gounico"
    DB_HOST : "host.docker.internal"
    DB_PORT : "3306"